M48
; DRILL file {KiCad 7.0.1} date 2023-05-03T08:50:31 CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-03T08:50:31+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X25.207Y-50.08
X25.207Y-141.52
X140.015Y-50.08
X140.015Y-141.52
T0
M30
